# Generated by Django 5.0.2 on 2024-02-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='product_default.jpg', upload_to='products/cover/%Y/%m/%d'),
        ),
    ]
