# Generated by Django 5.0.2 on 2024-02-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='media/product_default.jpg', upload_to='products/cover/%Y/%m/%d'),
        ),
    ]
